"""empty message

Revision ID: 00558b257826
Revises: 6ab29ee80f55
Create Date: 2019-12-14 02:22:35.063296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00558b257826'
down_revision = '6ab29ee80f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sizes',
        sa.Column('value', sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint('value'),
    )
    op.add_column('varieties', sa.Column('size_id', sa.String(length=3), nullable=True))
    op.drop_constraint('varieties_color_id_fkey', 'varieties', type_='foreignkey')
    op.drop_constraint('varieties_product_id_fkey', 'varieties', type_='foreignkey')
    op.create_foreign_key(
        None, 'varieties', 'colors', ['color_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        None, 'varieties', 'sizes', ['size_id'], ['value'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        None, 'varieties', 'products', ['product_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_column('varieties', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'varieties',
        sa.Column('size', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, 'varieties', type_='foreignkey')
    op.drop_constraint(None, 'varieties', type_='foreignkey')
    op.drop_constraint(None, 'varieties', type_='foreignkey')
    op.create_foreign_key(
        'varieties_product_id_fkey', 'varieties', 'products', ['product_id'], ['id']
    )
    op.create_foreign_key(
        'varieties_color_id_fkey', 'varieties', 'colors', ['color_id'], ['id']
    )
    op.drop_column('varieties', 'size_id')
    op.drop_table('sizes')
    # ### end Alembic commands ###
