"""empty message

Revision ID: 1600d0c093c1
Revises: ec6ad53fb9a8
Create Date: 2019-12-24 01:24:41.330840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1600d0c093c1'
down_revision = 'ec6ad53fb9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('time', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'time')
    # ### end Alembic commands ###
