"""empty message

Revision ID: 17f8f6ecd608
Revises: 8d2b0d4ada48
Create Date: 2020-01-07 13:16:17.255494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f8f6ecd608'
down_revision = '8d2b0d4ada48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('internal', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'internal')
    # ### end Alembic commands ###
