"""empty message

Revision ID: 1d13ba6044e3
Revises: 6a4a0517d55b
Create Date: 2019-12-24 20:51:27.226990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d13ba6044e3'
down_revision = '6a4a0517d55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'timestamp')
    # ### end Alembic commands ###
