"""empty message

Revision ID: 1d3051931992
Revises: f3c0d5e15dc9
Create Date: 2019-12-14 20:44:14.032751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3051931992'
down_revision = 'f3c0d5e15dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('varieties', 'color_value',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.alter_column('varieties', 'size_id',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.drop_constraint('varieties_product_id_size_id_color_value_key', 'varieties', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('varieties_product_id_size_id_color_value_key', 'varieties', ['product_id', 'size_id', 'color_value'])
    op.alter_column('varieties', 'size_id',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('varieties', 'color_value',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    # ### end Alembic commands ###
