"""empty message

Revision ID: 1db4decd77d3
Revises: f1f309238e2a
Create Date: 2019-12-14 18:34:51.972020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db4decd77d3'
down_revision = 'f1f309238e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, 'varieties', ['product_id', 'size_id', 'color_value']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'varieties', type_='unique')
    # ### end Alembic commands ###
