"""empty message

Revision ID: 1f1c8e85ebce
Revises: 1db4decd77d3
Create Date: 2019-12-14 20:22:18.008186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1c8e85ebce'
down_revision = '1db4decd77d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('varieties', 'color_value',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('varieties', 'size_id',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('varieties', 'size_id',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('varieties', 'color_value',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    # ### end Alembic commands ###
