"""Lift some more constraints

Revision ID: 22ec8260152c
Revises: 97b4e9faecc5
Create Date: 2020-06-12 18:46:14.284762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ec8260152c'
down_revision = '97b4e9faecc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'people_required',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activities', 'working_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'working_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('activities', 'people_required',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
