"""empty message

Revision ID: 2592727793d4
Revises: 4024ea77b26e
Create Date: 2019-11-20 15:16:30.514091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2592727793d4'
down_revision = '4024ea77b26e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'applications', 'comment', existing_type=sa.VARCHAR(length=1024), nullable=True
    )
    op.alter_column(
        'applications',
        'telegram_username',
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
    )
    op.drop_constraint(
        'applications_applicant_email_fkey', 'applications', type_='foreignkey'
    )
    op.drop_constraint(
        'applications_activity_id_fkey', 'applications', type_='foreignkey'
    )
    op.create_foreign_key(
        None,
        'applications',
        'accounts',
        ['applicant_email'],
        ['email'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        None, 'applications', 'activities', ['activity_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(
        'applications_activity_id_fkey',
        'applications',
        'activities',
        ['activity_id'],
        ['id'],
    )
    op.create_foreign_key(
        'applications_applicant_email_fkey',
        'applications',
        'accounts',
        ['applicant_email'],
        ['email'],
    )
    op.alter_column(
        'applications',
        'telegram_username',
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
    )
    op.alter_column(
        'applications', 'comment', existing_type=sa.VARCHAR(length=1024), nullable=False
    )
    # ### end Alembic commands ###
