"""empty message

Revision ID: 2664aaf602ab
Revises: 95c2a0076d4c
Create Date: 2020-01-05 18:20:54.018089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2664aaf602ab'
down_revision = '95c2a0076d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedback_application_id_fkey', 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transactions_feedback_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'feedback', ['feedback_id'], ['application_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_feedback_id_fkey', 'transactions', 'feedback', ['feedback_id'], ['application_id'])
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key('feedback_application_id_fkey', 'feedback', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###
