"""empty message

Revision ID: 28eebf427242
Revises: 69db9924ec1c
Create Date: 2020-03-26 17:49:57.763019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28eebf427242'
down_revision = '69db9924ec1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_stock_change_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'stock_changes', ['stock_change_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_stock_change_id_fkey', 'transactions', 'stock_changes', ['stock_change_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
