"""empty message

Revision ID: 563841f14d37
Revises: 1600d0c093c1
Create Date: 2019-12-24 01:28:40.073118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "563841f14d37"
down_revision = "1600d0c093c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("accounts", "university_status", new_column_name="group")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("accounts", "group", new_column_name="university_status")
    # ### end Alembic commands ###
