"""empty message

Revision ID: 687698d9105f
Revises: ed3e8a2fe2dd
Create Date: 2019-12-23 19:32:49.382720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687698d9105f'
down_revision = 'ed3e8a2fe2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('varieties', sa.Column('color', sa.String(length=6), nullable=True))
    op.add_column('varieties', sa.Column('size', sa.String(length=3), nullable=True))
    op.drop_constraint('varieties_size_id_fkey', 'varieties', type_='foreignkey')
    op.drop_constraint('varieties_color_value_fkey', 'varieties', type_='foreignkey')
    op.create_foreign_key(
        None, 'varieties', 'sizes', ['size'], ['value'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        None, 'varieties', 'colors', ['color'], ['value'], ondelete='CASCADE'
    )
    op.drop_column('varieties', 'size_id')
    op.drop_column('varieties', 'color_value')
    # ### end Alembic commands ###
    op.alter_column(
        table_name='activities',
        column_name='application_deadline',
        type_=sa.DateTime(timezone=True),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'varieties',
        sa.Column(
            'color_value', sa.VARCHAR(length=6), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        'varieties',
        sa.Column('size_id', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, 'varieties', type_='foreignkey')
    op.drop_constraint(None, 'varieties', type_='foreignkey')
    op.create_foreign_key(
        'varieties_color_value_fkey',
        'varieties',
        'colors',
        ['color_value'],
        ['value'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        'varieties_size_id_fkey',
        'varieties',
        'sizes',
        ['size_id'],
        ['value'],
        ondelete='CASCADE',
    )
    op.drop_column('varieties', 'size')
    op.drop_column('varieties', 'color')
    # ### end Alembic commands ###
    op.alter_column(
        table_name='activities', column_name='application_deadline', type_=sa.DateTime()
    )
