"""empty message

Revision ID: 69db9924ec1c
Revises: 3858db2e09c9
Create Date: 2020-03-24 13:50:36.205035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69db9924ec1c'
down_revision = '3858db2e09c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_stock_change_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'stock_changes', ['stock_change_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_stock_change_id_fkey', 'transactions', 'stock_changes', ['stock_change_id'], ['id'])
    # ### end Alembic commands ###
