"""empty message

Revision ID: 6a4a0517d55b
Revises: 563841f14d37
Create Date: 2019-12-24 14:14:17.783567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6a4a0517d55b"
down_revision = "563841f14d37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("payload", sa.JSON(), nullable=True))
    op.drop_constraint(
        "notifications_activity_id_fkey", "notifications", type_="foreignkey"
    )
    op.drop_constraint(
        "notifications_project_id_fkey", "notifications", type_="foreignkey"
    )
    op.drop_constraint(
        "notifications_product_id_fkey", "notifications", type_="foreignkey"
    )
    op.drop_column("notifications", "activity_id")
    op.drop_column("notifications", "project_id")
    op.drop_column("notifications", "product_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "notifications",
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "notifications",
        sa.Column("activity_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "notifications_product_id_fkey",
        "notifications",
        "products",
        ["product_id"],
        ["id"],
    )
    op.create_foreign_key(
        "notifications_project_id_fkey",
        "notifications",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.create_foreign_key(
        "notifications_activity_id_fkey",
        "notifications",
        "activities",
        ["activity_id"],
        ["id"],
    )
    op.drop_column("notifications", "payload")
    # ### end Alembic commands ###
