"""empty message

Revision ID: 6ab29ee80f55
Revises: 98a9e432a764
Create Date: 2019-12-14 01:58:29.327721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab29ee80f55'
down_revision = '98a9e432a764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'colors', 'value', existing_type=sa.VARCHAR(length=6), nullable=False
    )
    op.create_unique_constraint(None, 'colors', ['value'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'colors', type_='unique')
    op.alter_column(
        'colors', 'value', existing_type=sa.VARCHAR(length=6), nullable=True
    )
    # ### end Alembic commands ###
