"""Update hourly rate

Revision ID: 7186f22b9d26
Revises: 5a4cf17483a5
Create Date: 2024-01-12 12:18:34.253593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7186f22b9d26'
down_revision = '5a4cf17483a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reward policy', 'activities')
    op.create_check_constraint('reward policy',
                               'activities',
                               '(fixed_reward AND working_hours = 1) OR (NOT fixed_reward AND reward_rate = 100)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reward policy', 'activities')
    op.create_check_constraint('reward policy',
                               'activities',
                               '(fixed_reward AND working_hours = 1) OR (NOT fixed_reward AND reward_rate = 70)')
    # ### end Alembic commands ###
