"""empty message

Revision ID: 7c2e7839ae2d
Revises: ac8d07472c45
Create Date: 2019-12-23 02:13:48.101419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7c2e7839ae2d"
down_revision = "ac8d07472c45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "activities", "reward_rate", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "activities", "working_hours", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "projects",
        "creation_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_constraint(
        "transactions_account_email_fkey", "transactions", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "transactions",
        "accounts",
        ["account_email"],
        ["email"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.create_foreign_key(
        "transactions_account_email_fkey",
        "transactions",
        "accounts",
        ["account_email"],
        ["email"],
    )
    op.alter_column(
        "projects", "creation_time", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "activities", "working_hours", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "activities", "reward_rate", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
