"""empty message

Revision ID: 8d2b0d4ada48
Revises: c11bd28c9451
Create Date: 2020-01-06 16:30:42.605048

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8d2b0d4ada48'
down_revision = 'c11bd28c9451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'applications', 'actual_hours', existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'applications', 'actual_hours', existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
