"""empty message

Revision ID: 98a9e432a764
Revises: 912d0366a555
Create Date: 2019-12-13 22:37:16.599031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "98a9e432a764"
down_revision = "912d0366a555"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "competences", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "competences", type_="unique")
    # ### end Alembic commands ###
