"""empty message

Revision ID: a70d4740fbc6
Revises: 7c2e7839ae2d
Create Date: 2019-12-23 02:29:13.377260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70d4740fbc6'
down_revision = '7c2e7839ae2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedback_competence_feedback_id_fkey', 'feedback_competence', type_='foreignkey')
    op.drop_constraint('transactions_feedback_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('feedback', 'id')
    op.drop_column('reports', 'id')
    op.create_unique_constraint(None, 'feedback', ['application_id'])
    op.create_unique_constraint(None, 'reports', ['application_id'])
    op.create_foreign_key(None, 'feedback_competence', 'feedback', ['feedback_id'], ['application_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'feedback', ['feedback_id'], ['application_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'feedback_competence', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='unique')
    op.drop_constraint(None, 'feedback', type_='unique')
    op.add_column('reports', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('feedback', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('feedback_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.create_foreign_key('transactions_feedback_id_fkey', 'transactions', 'feedback', ['feedback_id'], ['id'])
    op.create_foreign_key('feedback_competence_feedback_id_fkey', 'feedback_competence', 'feedback', ['feedback_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
