"""empty message

Revision ID: b96e8f463143
Revises: 17f8f6ecd608
Create Date: 2020-01-07 16:42:17.809020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96e8f463143'
down_revision = '17f8f6ecd608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'static_files', sa.Column('owner_email', sa.String(length=128), nullable=True)
    )
    op.create_foreign_key(
        None, 'static_files', 'accounts', ['owner_email'], ['email'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'static_files', type_='foreignkey')
    op.drop_column('static_files', 'owner_email')
    # ### end Alembic commands ###
