"""empty message

Revision ID: c11bd28c9451
Revises: 297d3ef73ef1
Create Date: 2020-01-06 13:57:03.280902

"""
import json
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c11bd28c9451'
down_revision = '297d3ef73ef1'
branch_labels = None
depends_on = None


DEFAULT_NOTIFICATIONS = {
    'innostore': 'off',
    'volunteering': 'off',
    'project_creation': 'off',
    'administration': 'off',
    'service': 'email',
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=json.dumps(DEFAULT_NOTIFICATIONS)))
    # ### end Alembic commands ###
    op.alter_column(
        table_name='notifications',
        column_name='payload',
        type_=postgresql.JSONB(astext_type=sa.Text())
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'notification_settings')
    # ### end Alembic commands ###
    op.alter_column(
        table_name='notifications',
        column_name='payload',
        type_=sa.JSON()
    )
