"""empty message

Revision ID: f3c0d5e15dc9
Revises: 1f1c8e85ebce
Create Date: 2019-12-14 20:26:04.275894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c0d5e15dc9'
down_revision = '1f1c8e85ebce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_images_variety_id_fkey', 'product_images', type_='foreignkey')
    op.drop_constraint('product_images_image_id_fkey', 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'varieties', ['variety_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_images', 'static_files', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('stock_changes_account_email_fkey', 'stock_changes', type_='foreignkey')
    op.drop_constraint('stock_changes_variety_id_fkey', 'stock_changes', type_='foreignkey')
    op.create_foreign_key(None, 'stock_changes', 'varieties', ['variety_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stock_changes', 'accounts', ['account_email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_changes', type_='foreignkey')
    op.drop_constraint(None, 'stock_changes', type_='foreignkey')
    op.create_foreign_key('stock_changes_variety_id_fkey', 'stock_changes', 'varieties', ['variety_id'], ['id'])
    op.create_foreign_key('stock_changes_account_email_fkey', 'stock_changes', 'accounts', ['account_email'], ['email'])
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key('product_images_image_id_fkey', 'product_images', 'static_files', ['image_id'], ['id'])
    op.create_foreign_key('product_images_variety_id_fkey', 'product_images', 'varieties', ['variety_id'], ['id'])
    # ### end Alembic commands ###
